workflows:
  expo-apk:
    name: Expo Android APK Build
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - name: Install Expo & EAS CLI
        script: |
          npm install -g expo-cli eas-cli
          npm install
      - name: Build APK using EAS
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/**/*.apk
