workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
